/*Alertas*/
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

/*Autenticacion: Iniciar Sesion */
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

/*CRUD DE EMPLEADOS*/
export const LISTAR_EMPLEADOS = 'LISTAR_EMPLEADOS';
export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO';
export const VALIDAR_EMPLEADO = 'VALIDAR_EMPLEADO';
export const ACTUAL_EMPLEADO = 'ACTUAL_EMPLEADO';
export const ACTUALIZAR_EMPLEADO = 'ACTUALIZAR_EMPLEADO';
export const ELIMINAR_EMPLEADO = 'ELIMINAR_EMPLEADO';
export const BUSCAR_EMPLEADO = 'BUSCAR_EMPLEADO';
export const LIMPIAR_EMPLEADO_SELECCIONADO= 'LIMPIAR_EMPLEADO_SELECCIONADO';

/*CRUD DE CLIENTES*/
export const LISTAR_CLIENTES = 'LISTAR_CLIENTES';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const VALIDAR_CLIENTE = 'VALIDAR_CLIENTE';
export const ACTUAL_CLIENTE = 'ACTUAL_CLIENTE';
export const ACTUALIZAR_CLIENTE = 'ACTUALIZAR_CLIENTE';
export const ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE';
export const BUSCAR_CLIENTE = 'BUSCAR_CLIENTE';
export const LIMPIAR_CLIENTE_SELECCIONADO= 'LIMPIAR_CLIENTE_SELECCIONADO';

/*CRUD DE PROVEEDORES*/
export const LISTAR_PROVEEDORES = 'LISTAR_PROVEEDORES';
export const AGREGAR_PROVEEDOR = 'AGREGAR_PROVEEDOR';
export const VALIDAR_PROVEEDOR = 'VALIDAR_PROVEEDOR';
export const ACTUAL_PROVEEDOR = 'ACTUAL_PROVEEDOR';
export const ACTUALIZAR_PROVEEDOR = 'ACTUALIZAR_PROVEEDOR';
export const ELIMINAR_PROVEEDOR = 'ELIMINAR_PROVEEDOR';
export const BUSCAR_PROVEEDOR = 'BUSCAR_PROVEEDOR';
export const LIMPIAR_PROVEEDOR_SELECCIONADO= 'LIMPIAR_PROVEEDOR_SELECCIONADO';

/*CRUD DE USUARIOS*/
export const LISTAR_USUARIOS = 'LISTAR_USUARIOS';
export const SELECT_EMPLEADOS = 'SELECT_EMPLEADOS';
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const VALIDAR_USUARIO = 'VALIDAR_USUARIO';
export const ACTUAL_USUARIO = 'ACTUAL_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const LIMPIAR_USUARIO_SELECCIONADO = 'LIMPIAR_USUARIO_SELECCIONADO';