/*Alertas*/
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

/*Autenticacion: Iniciar Sesion */
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

/*CRUD DE EMPLEADOS*/
export const LISTAR_EMPLEADOS = 'LISTAR_EMPLEADOS';
export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO';
export const VALIDAR_EMPLEADO = 'VALIDAR_EMPLEADO';
export const ACTUAL_EMPLEADO = 'ACTUAL_EMPLEADO';
export const ACTUALIZAR_EMPLEADO = 'ACTUALIZAR_EMPLEADO';
export const ELIMINAR_EMPLEADO = 'ELIMINAR_EMPLEADO';